[["/Users/mereyazhibekova/anaconda3/lib/python3.11/site-packages/service_identity/__init__.py",[false,[["CertificateError",true,2,["CertificateError","/Users/mereyazhibekova/anaconda3/lib/python3.11/site-packages/service_identity/exceptions.py",5]],["SubjectAltNameWarning",true,2,["SubjectAltNameWarning","/Users/mereyazhibekova/anaconda3/lib/python3.11/site-packages/service_identity/exceptions.py",5]],["VerificationError",true,2,["VerificationError","/Users/mereyazhibekova/anaconda3/lib/python3.11/site-packages/service_identity/exceptions.py",5]]]]]]